headr <- read.csv("Data/household_power_consumption.txt",header=FALSE,sep=";",nrows = 1)
expdata <- read.csv("Data/household_power_consumption.txt",header=TRUE,sep=";",skip=66636,nrows = 2880)
colnames(expdata) <- unlist(headr)
par(mfrow=c(2,2))
plot(expdata$DateTime,expdata$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(expdata$DateTime,expdata$Voltage,type="l",xlab="datetime",ylab="Voltage")
plot(expdata$DateTime,expdata$Sub_metering_1,type="l",ylim=c(0,max(expdata$Sub_metering_1)),xlab="",ylab="Global sub metering")
points(expdata$DateTime,expdata$Sub_metering_2,type="l",ylim=c(0,max(expdata$Sub_metering_1)),xlab="",ylab="Global sub metering",col="red")
points(expdata$DateTime,expdata$Sub_metering_3,type="l",ylim=c(0,max(expdata$Sub_metering_1)),xlab="",ylab="Global sub metering",col="blue")
legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1,col=c("black","red","blue"),cex=0.75,bty="n")
plot(expdata$DateTime,expdata$Global_reactive_power,type="l",xlab="datetime",ylab="Global reactive power",ylim=c(0,max(expdata$Global_reactive_power)))

